name: Build and Release

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Crystal
      uses: crystal-lang/install-crystal@v1
      with:
        crystal: latest
    
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libgc-dev
    
    - name: Build injector library
      run: make injector
    
    - name: Build CLI application
      run: make cli
    
    - name: Verify builds
      run: |
        ls -la bin/
        ls -la lib/
        file bin/cli
        file lib/libinjector.so
    
    - name: Create artifact directory
      run: |
        mkdir -p artifact/bin
        mkdir -p artifact/lib
        cp bin/cli artifact/bin/
        cp lib/libinjector.so artifact/lib/
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: network-cli-binaries
        path: artifact/
        retention-days: 30